import {
  Project,
  Application,
  StudentProfile,
  PortfolioEntry,
  DigitalCertificate,
  PredefinedSkill,
  PredefinedCategory,
} from '../types';

export const PREDEFINED_SKILLS: PredefinedSkill[] = [
  'HTML',
  'CSS',
  'JavaScript',
  'TypeScript',
  'React',
  'Node.js',
  'Python',
  'Java',
  'SQL',
  'Git',
  'Figma',
  'Adobe XD',
  'Google Ads',
  'SEO',
  'Content Writing',
  'Video Editing',
  'Data Analysis',
  'Excel',
  'Copywriting',
  'Mailchimp',
  'Marketing',
  'Financial Modelling',
  'PowerPoint',
  'Brand Strategy',
  'Content Strategy',
  'Shopify',
  'Pandas',
  'Tableau',
];

export const PREDEFINED_CATEGORIES: PredefinedCategory[] = [
  'Frontend',
  'Backend',
  'Full-stack',
  'UI/UX',
  'Mobile',
  'AI/ML',
  'Marketing',
  'Content',
  'Business',
  'Data',
  'Design',
];

export const MOCK_STUDENT_PROFILE: StudentProfile = {
  id: 'stu-1',
  userId: 'user-stu-1',
  fullName: 'Alex Chen',
  university: 'UCL (University College London)',
  major: 'BSc Business Management',
  year: 4,
  location: 'London, UK / Ho Chi Minh City',
  bio: 'Final-year Business Management student specialising in marketing and brand strategy. Passionate about helping SMEs build clear, effective brand identities and content systems. Available for short-term projects 20h/week.',
  githubUrl: 'https://github.com/alexchen-dev',
  linkedInUrl: 'https://linkedin.com/in/alexchen-demo',
  rating: 4.7,
  reviewCount: 8,
  completedProjectsCount: 8,
  availability: 'Available — up to 20h/week',
  availableUntil: '30 May 2025',
  skills: {
    expert: ['Figma', 'Brand Strategy', 'Content Strategy'],
    proficient: ['Excel', 'PowerPoint', 'Mailchimp', 'Data Analysis', 'SEO', 'Copywriting'],
    familiar: ['SQL', 'HTML', 'CSS'],
  },
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: 'Brand Identity Redesign',
    description:
      'Create a complete brand identity for Artisan Coffee Co., an independent specialty coffee roaster based in Shoreditch & HCM. The brand should feel premium but approachable — targeting coffee enthusiasts aged 25-40 who value craft and sustainability.',
    smeName: 'Sarah Mitchell',
    smeCompany: 'Artisan Coffee Co.',
    smeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    category: 'Design',
    requiredSkills: ['Figma', 'Brand Strategy', 'Content Strategy', 'Copywriting'],
    budgetVnd: 14400000, // equivalent ~£480 in VND (~14.4M VND)
    durationWeeks: 4,
    location: 'Remote',
    status: 'IN_PROGRESS',
    maxApplicants: 1,
    createdAt: '2024-11-15',
    escrowStatus: 'HELD',
    autoAcceptDaysRemaining: 28,
    acceptedStudentId: 'stu-1',
    acceptedStudentName: 'Alex Chen',
    acceptedStudentUniversity: 'UCL',
    applicantCount: 5,
    milestones: [
      {
        id: 'ms-1-1',
        projectId: 'proj-1',
        title: 'Brand discovery & mood board',
        description: 'Initial market positioning, competitor analysis, and mood board visual direction.',
        deadline: '28 Nov 2024',
        orderIndex: 1,
        status: 'ACCEPTED',
        deliverableUrl: 'https://figma.com/file/sample-moodboard-artisan',
        submittedAt: '2024-11-27',
        amountVnd: 3600000,
      },
      {
        id: 'ms-1-2',
        projectId: 'proj-1',
        title: 'Logo concepts (3 directions)',
        description: 'Vector logo concepts including wordmark, icon badge, and color palette explorations.',
        deadline: '05 Dec 2024',
        orderIndex: 2,
        status: 'ACCEPTED',
        deliverableUrl: 'https://figma.com/file/logo-concepts-round2',
        submittedAt: '2024-12-04',
        amountVnd: 3600000,
      },
      {
        id: 'ms-1-3',
        projectId: 'proj-1',
        title: 'Refined logo + brand guidelines',
        description: 'Final logo files (SVG/PNG/PDF) and complete brand usage guidelines document.',
        deadline: '12 Dec 2024',
        orderIndex: 3,
        status: 'SUBMITTED',
        deliverableUrl: 'https://drive.google.com/drive/folders/artisan-brand-final',
        submittedAt: '2024-12-11',
        amountVnd: 3600000,
      },
      {
        id: 'ms-1-4',
        projectId: 'proj-1',
        title: 'Collateral assets (cards, letterhead, packaging)',
        description: 'Print-ready business cards, packaging stickers, and digital social media templates.',
        deadline: '18 Dec 2024',
        orderIndex: 4,
        status: 'PENDING',
        amountVnd: 3600000,
      },
    ],
  },
  {
    id: 'proj-2',
    title: 'Python Data Pipeline & Dashboard',
    description:
      'Build a data pipeline ingesting CSV/API data, transform with Pandas, load to PostgreSQL, and create a Tableau/Dashboard for sales metrics.',
    smeName: 'David Lee',
    smeCompany: 'DataLens Analytics',
    smeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    category: 'Data',
    requiredSkills: ['Python', 'Pandas', 'SQL', 'Tableau', 'Data Analysis'],
    budgetVnd: 18000000, // ~£600
    durationWeeks: 4,
    location: 'Remote',
    status: 'OPEN',
    maxApplicants: 2,
    createdAt: '2024-12-01',
    escrowStatus: 'PENDING',
    applicantCount: 9,
    milestones: [
      {
        id: 'ms-2-1',
        projectId: 'proj-2',
        title: 'Data ingestion script & DB schema',
        description: 'Clean Python script for API ingestion and PostgreSQL schema definition.',
        deadline: '10 Jan 2025',
        orderIndex: 1,
        status: 'PENDING',
        amountVnd: 9000000,
      },
      {
        id: 'ms-2-2',
        projectId: 'proj-2',
        title: 'Interactive Sales Dashboard',
        description: 'Completed interactive dashboard displaying key sales metrics and monthly trends.',
        deadline: '24 Jan 2025',
        orderIndex: 2,
        status: 'PENDING',
        amountVnd: 9000000,
      },
    ],
  },
  {
    id: 'proj-3',
    title: 'Shopify Store Redesign',
    description:
      'Redesign our Shopify storefront for a Scandinavian homeware brand. Improve conversion rate and mobile user experience.',
    smeName: 'Astrid Lindgren',
    smeCompany: 'Nordic Goods',
    smeAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    category: 'Frontend',
    requiredSkills: ['Figma', 'Shopify', 'CSS', 'HTML', 'JavaScript'],
    budgetVnd: 11400000, // ~£380
    durationWeeks: 3,
    location: 'Remote',
    status: 'OPEN',
    maxApplicants: 1,
    createdAt: '2024-12-05',
    escrowStatus: 'PENDING',
    applicantCount: 14,
    milestones: [
      {
        id: 'ms-3-1',
        projectId: 'proj-3',
        title: 'UI Audit & Figma Wireframes',
        description: 'Audit current Shopify theme and produce mobile-first wireframes.',
        deadline: '15 Jan 2025',
        orderIndex: 1,
        status: 'PENDING',
        amountVnd: 5700000,
      },
      {
        id: 'ms-3-2',
        projectId: 'proj-3',
        title: 'Liquid & CSS Theme Customization',
        description: 'Implement redesigned sections in live Shopify theme test environment.',
        deadline: '28 Jan 2025',
        orderIndex: 2,
        status: 'PENDING',
        amountVnd: 5700000,
      },
    ],
  },
  {
    id: 'proj-4',
    title: 'Email Marketing Campaign & Lead Magnet',
    description:
      'Plan and execute a 6-email welcome sequence and 2 promotional campaigns for our floristry subscription box service.',
    smeName: 'Chloe Bennett',
    smeCompany: 'Petal & Thread',
    smeAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    category: 'Marketing',
    requiredSkills: ['Copywriting', 'Mailchimp', 'Marketing', 'Content Writing'],
    budgetVnd: 6000000, // ~£200
    durationWeeks: 2,
    location: 'Remote',
    status: 'OPEN',
    maxApplicants: 1,
    createdAt: '2024-12-10',
    escrowStatus: 'PENDING',
    applicantCount: 7,
    milestones: [
      {
        id: 'ms-4-1',
        projectId: 'proj-4',
        title: 'Email Sequence Copywriting',
        description: 'Draft 6 onboarding emails and lead magnet PDF copy.',
        deadline: '20 Jan 2025',
        orderIndex: 1,
        status: 'PENDING',
        amountVnd: 3000000,
      },
      {
        id: 'ms-4-2',
        projectId: 'proj-4',
        title: 'Mailchimp Template & Automation Setup',
        description: 'Set up responsive templates and test automated email triggers.',
        deadline: '27 Jan 2025',
        orderIndex: 2,
        status: 'PENDING',
        amountVnd: 3000000,
      },
    ],
  },
  {
    id: 'proj-5',
    title: 'Financial Model — Seed Round',
    description:
      'Build a 3-statement financial model and investor-ready deck for a pre-seed tech startup raising 500k USD.',
    smeName: 'Marcus Vance',
    smeCompany: 'Startup Finance Hub',
    smeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    category: 'Business',
    requiredSkills: ['Excel', 'Financial Modelling', 'PowerPoint'],
    budgetVnd: 15000000, // ~£500
    durationWeeks: 3,
    location: 'Remote',
    status: 'OPEN',
    maxApplicants: 1,
    createdAt: '2024-12-12',
    escrowStatus: 'PENDING',
    applicantCount: 4,
    milestones: [
      {
        id: 'ms-5-1',
        projectId: 'proj-5',
        title: 'Financial Model Excel Sheet',
        description: 'Dynamic 3-statement financial model with revenue levers and expense assumptions.',
        deadline: '18 Jan 2025',
        orderIndex: 1,
        status: 'PENDING',
        amountVnd: 10000000,
      },
      {
        id: 'ms-5-2',
        projectId: 'proj-5',
        title: 'Investor Pitch Deck Financial Slides',
        description: '5 high-impact pitch deck slides summarizing financials and unit economics.',
        deadline: '25 Jan 2025',
        orderIndex: 2,
        status: 'PENDING',
        amountVnd: 5000000,
      },
    ],
  },
  {
    id: 'proj-6',
    title: 'UX Audit & Mobile App Wireframes',
    description:
      'Conduct a full UX audit of our patient-facing mobile app and produce annotated wireframes for the redesigned user flows.',
    smeName: 'Dr. Emily Watson',
    smeCompany: 'HealthApp UK',
    smeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    category: 'UI/UX',
    requiredSkills: ['Figma', 'Adobe XD', 'UI/UX'],
    budgetVnd: 12000000,
    durationWeeks: 3,
    location: 'Remote',
    status: 'OPEN',
    maxApplicants: 1,
    createdAt: '2024-12-14',
    escrowStatus: 'PENDING',
    applicantCount: 8,
    milestones: [],
  },
  {
    id: 'proj-7',
    title: 'Social Media Strategy & Content Deck',
    description:
      'Develop a 6-week Instagram content strategy and create 30 high-converting posts with captions for our interior design studio.',
    smeName: 'Bao Nguyen',
    smeCompany: 'Bloom Interiors',
    smeAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    category: 'Content',
    requiredSkills: ['Content Strategy', 'Copywriting', 'Figma', 'Marketing'],
    budgetVnd: 7500000,
    durationWeeks: 2,
    location: 'Remote',
    status: 'OPEN',
    maxApplicants: 2,
    createdAt: '2024-12-15',
    escrowStatus: 'PENDING',
    applicantCount: 11,
    milestones: [],
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-1',
    projectId: 'proj-2',
    projectTitle: 'Python Data Pipeline & Dashboard',
    studentId: 'stu-2',
    studentName: 'Nguyen Van A',
    studentUniversity: 'VNUHCM-UIT',
    studentMajor: 'Software Engineering',
    studentYear: 3,
    studentAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
    skills: ['Python', 'Pandas', 'SQL', 'Tableau'],
    matchScore: 80, // 4 out of 5 required skills
    matchingSkillsCount: 4,
    totalRequiredSkills: 5,
    status: 'SHORTLISTED',
    coverMessage:
      'I have 2 years of experience writing ETL data scripts in Python and Pandas during my coursework. I recently built a PostgreSQL & Metabase analytics pipeline for a university project.',
    appliedAt: '2024-12-03',
  },
  {
    id: 'app-2',
    projectId: 'proj-2',
    projectTitle: 'Python Data Pipeline & Dashboard',
    studentId: 'stu-3',
    studentName: 'Tran Thi B',
    studentUniversity: 'HCMUT (Bach Khoa)',
    studentMajor: 'Data Science',
    studentYear: 4,
    studentAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    skills: ['Python', 'Pandas', 'SQL', 'Data Analysis', 'Tableau'],
    matchScore: 100, // 5 out of 5 required skills
    matchingSkillsCount: 5,
    totalRequiredSkills: 5,
    status: 'APPLIED',
    coverMessage:
      'Data Science senior with strong expertise in PostgreSQL optimization and Tableau dashboard design. Looking forward to applying data modeling best practices.',
    appliedAt: '2024-12-04',
  },
  {
    id: 'app-3',
    projectId: 'proj-1',
    projectTitle: 'Brand Identity Redesign',
    studentId: 'stu-1',
    studentName: 'Alex Chen',
    studentUniversity: 'UCL',
    studentMajor: 'BSc Business Management',
    studentYear: 4,
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    skills: ['Figma', 'Brand Strategy', 'Content Strategy', 'Copywriting'],
    matchScore: 100,
    matchingSkillsCount: 4,
    totalRequiredSkills: 4,
    status: 'ACCEPTED',
    coverMessage:
      'I have designed brand guidelines for 3 local food & beverage startups in HCM City and London. Excited to help Artisan Coffee Co. stand out!',
    appliedAt: '2024-11-18',
  },
];

export const MOCK_PORTFOLIO_ENTRIES: PortfolioEntry[] = [
  {
    id: 'port-1',
    studentId: 'stu-1',
    projectTitle: 'Saigon Craft Beer — E-Commerce UI',
    smeCompany: 'Saigon Craft Brewery',
    smeName: 'Le Hoang Nam',
    role: 'Lead UI/UX & Brand Designer',
    duration: '3 weeks',
    skillsApplied: ['Figma', 'Brand Strategy', 'CSS', 'HTML'],
    deliverableUrl: 'https://figma.com/@alexchen/saigon-craft-beer',
    completedDate: '15 Oct 2024',
    verificationCode: 'SKILLBRIDGE-VERIFIED-88219',
  },
  {
    id: 'port-2',
    studentId: 'stu-1',
    projectTitle: 'EcoPack Packaging Identity & Web Copy',
    smeCompany: 'EcoPack Vietnam',
    smeName: 'Pham Thu Trang',
    role: 'Brand & Content Strategist',
    duration: '2 weeks',
    skillsApplied: ['Content Strategy', 'Copywriting', 'SEO'],
    deliverableUrl: 'https://drive.google.com/folder/ecopack-brand-assets',
    completedDate: '02 Nov 2024',
    verificationCode: 'SKILLBRIDGE-VERIFIED-99104',
  },
];

export const MOCK_CERTIFICATE: DigitalCertificate = {
  id: 'cert-1',
  certificateNumber: 'SB-CERT-2024-99104',
  studentName: 'Alex Chen',
  university: 'UCL (University College London)',
  projectTitle: 'EcoPack Packaging Identity & Web Copy',
  smeCompany: 'EcoPack Vietnam',
  issueDate: '02 Nov 2024',
  skillsVerified: ['Brand Strategy', 'Content Strategy', 'Copywriting', 'SEO'],
  verificationCode: 'SKILLBRIDGE-VERIFIED-99104',
};
